// <auto-generated />
using System;
using MediCore.API.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCore.API.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MediCoreDbContext))]
    [Migration("20260315192439_IPDAndBedAllocation")]
    partial class IPDAndBedAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.BedAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentAdmissionId")
                        .HasColumnType("int");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCleanedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaintenanceNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAdmissionId")
                        .IsUnique()
                        .HasFilter("[CurrentAdmissionId] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("BedAllocations");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.DailyIPDCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChargeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DoctorVisitCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LabCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MedicineCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NursingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProcedureCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoomCharge")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("AdmissionId");

                    b.ToTable("DailyIPDCharges");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.DischargeNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityRestrictions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Complications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalDiagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FollowUpWithDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("MedicinesAtDischarge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentSummary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("FollowUpWithDoctorId");

                    b.ToTable("DischargeNotes");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.PatientAdmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdmittingDoctorProfileId")
                        .HasColumnType("int");

                    b.Property<string>("AttendantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendantPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendantRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<string>("ChiefComplaints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRoomCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DischargedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitialDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdmittingDoctorProfileId");

                    b.HasIndex("BedId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DischargedByUserId");

                    b.HasIndex("PatientUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("PatientAdmissions");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedsPerRoom")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenities = "Basic bed, monitor, oxygen",
                            BedsPerRoom = 1,
                            ColorCode = "#ef4444",
                            Description = "Emergency care with basic monitoring",
                            FloorNumber = 0,
                            IsActive = true,
                            Name = "Emergency Ward",
                            PricePerDay = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Amenities = "ICU equipment, ventilator, advanced monitoring",
                            BedsPerRoom = 1,
                            ColorCode = "#dc2626",
                            Description = "Intensive Care Unit with advanced equipment",
                            FloorNumber = 0,
                            IsActive = true,
                            Name = "ICU",
                            PricePerDay = 8000m
                        },
                        new
                        {
                            Id = 3,
                            Amenities = "Neonatal equipment, incubator, advanced care",
                            BedsPerRoom = 1,
                            ColorCode = "#f97316",
                            Description = "Neonatal Intensive Care Unit",
                            FloorNumber = 0,
                            IsActive = true,
                            Name = "NICU",
                            PricePerDay = 10000m
                        },
                        new
                        {
                            Id = 4,
                            Amenities = "Basic amenities, bed, locker",
                            BedsPerRoom = 1,
                            ColorCode = "#3b82f6",
                            Description = "General male ward",
                            FloorNumber = 1,
                            IsActive = true,
                            Name = "General Ward Male",
                            PricePerDay = 1200m
                        },
                        new
                        {
                            Id = 5,
                            Amenities = "Basic amenities, bed, locker",
                            BedsPerRoom = 1,
                            ColorCode = "#8b5cf6",
                            Description = "General female ward",
                            FloorNumber = 1,
                            IsActive = true,
                            Name = "General Ward Female",
                            PricePerDay = 1200m
                        },
                        new
                        {
                            Id = 6,
                            Amenities = "AC, TV, shared bathroom",
                            BedsPerRoom = 2,
                            ColorCode = "#6366f1",
                            Description = "Semi-private accommodation",
                            FloorNumber = 2,
                            IsActive = true,
                            Name = "Semi-Private Room",
                            PricePerDay = 2500m
                        },
                        new
                        {
                            Id = 7,
                            Amenities = "AC, TV, refrigerator, sofa",
                            BedsPerRoom = 1,
                            ColorCode = "#22c55e",
                            Description = "Private accommodation",
                            FloorNumber = 3,
                            IsActive = true,
                            Name = "Private Room",
                            PricePerDay = 4500m
                        },
                        new
                        {
                            Id = 8,
                            Amenities = "AC, TV, refrigerator, sofa, attendant bed",
                            BedsPerRoom = 1,
                            ColorCode = "#10b981",
                            Description = "Deluxe private accommodation",
                            FloorNumber = 3,
                            IsActive = true,
                            Name = "Deluxe Room",
                            PricePerDay = 7000m
                        },
                        new
                        {
                            Id = 9,
                            Amenities = "Full suite, living area, kitchenette",
                            BedsPerRoom = 1,
                            ColorCode = "#0d9488",
                            Description = "Full suite with living area",
                            FloorNumber = 4,
                            IsActive = true,
                            Name = "Suite",
                            PricePerDay = 12000m
                        });
                });

            modelBuilder.Entity("MediCore.API.Modules.Communication.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MediCore.API.Modules.Doctor.Models.DoctorLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorProfileId");

                    b.ToTable("DoctorLeaves");
                });

            modelBuilder.Entity("MediCore.API.Modules.Doctor.Models.DoctorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EveningEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("EveningStart")
                        .HasColumnType("time");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<bool>("HasEveningShift")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPatientsPerDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("MorningEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("MorningStart")
                        .HasColumnType("time");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("DoctorProfiles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Finance.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<decimal>("GSTAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InsuranceDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MediCore.API.Modules.Laboratory.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CriticalAlert")
                        .HasColumnType("bit");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleCollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("LabOrders");
                });

            modelBuilder.Entity("MediCore.API.Modules.Laboratory.Models.LabTestMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NormalRange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TurnaroundTimeHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LabTestMasters");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AppointmentRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ConsultationStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("FeedbackEmailSent")
                        .HasColumnType("bit");

                    b.Property<bool>("FeedbackSubmitted")
                        .HasColumnType("bit");

                    b.Property<int?>("FollowUpAppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("FollowUpBooked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FollowUpReminderSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstVisit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVideoConsultation")
                        .HasColumnType("bit");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("int");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceptionistNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.Property<string>("TokenNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VideoEndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VideoJoinedByPatientAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoRoomUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VideoStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorProfileId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.AppointmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFirstVisit")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreferredDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ReceptionistNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppointmentRequests");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.OtpRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OtpRecords");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Advice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DispensedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("bit");

                    b.Property<string>("MedicinesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.Vitals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int?>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Pulse")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordedById")
                        .HasColumnType("int");

                    b.Property<int?>("SpO2")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vitals");
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7414),
                            Description = "General health consultations",
                            FloorNumber = 1,
                            Icon = "🏥",
                            IsActive = true,
                            Name = "General Medicine"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7426),
                            Description = "Heart care",
                            FloorNumber = 2,
                            Icon = "❤️",
                            IsActive = true,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7430),
                            Description = "Brain care",
                            FloorNumber = 2,
                            Icon = "🧠",
                            IsActive = true,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7434),
                            Description = "Bone care",
                            FloorNumber = 3,
                            Icon = "🦴",
                            IsActive = true,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7438),
                            Description = "Children care",
                            FloorNumber = 1,
                            Icon = "👶",
                            IsActive = true,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7442),
                            Description = "Women health",
                            FloorNumber = 4,
                            Icon = "🌸",
                            IsActive = true,
                            Name = "Gynecology"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7446),
                            Description = "Skin care",
                            FloorNumber = 2,
                            Icon = "✨",
                            IsActive = true,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7450),
                            Description = "Eye care",
                            FloorNumber = 1,
                            Icon = "👁️",
                            IsActive = true,
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7454),
                            Description = "Ear nose throat",
                            FloorNumber = 3,
                            Icon = "👂",
                            IsActive = true,
                            Name = "ENT"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 15, 19, 24, 37, 668, DateTimeKind.Utc).AddTicks(7457),
                            Description = "Mental health",
                            FloorNumber = 4,
                            Icon = "🧘",
                            IsActive = true,
                            Name = "Psychiatry"
                        });
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.PatientFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorRating")
                        .HasColumnType("int");

                    b.Property<int>("FacilityRating")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<int>("PatientUserId")
                        .HasColumnType("int");

                    b.Property<int>("StaffRating")
                        .HasColumnType("int");

                    b.Property<bool>("WouldRecommend")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorProfileId");

                    b.HasIndex("PatientUserId");

                    b.ToTable("PatientFeedbacks");
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PatientProfiles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Pharmacy.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.RefreshToken", b =>
                {
                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.UserRole", b =>
                {
                    b.HasOne("MediCore.API.Modules.Auth.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.BedAllocation", b =>
                {
                    b.HasOne("MediCore.API.Modules.Bed.Models.PatientAdmission", "CurrentAdmission")
                        .WithOne()
                        .HasForeignKey("MediCore.API.Modules.Bed.Models.BedAllocation", "CurrentAdmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediCore.API.Modules.Bed.Models.Room", "Room")
                        .WithMany("Beds")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Bed.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentAdmission");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.DailyIPDCharge", b =>
                {
                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Bed.Models.PatientAdmission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Admission");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.DischargeNote", b =>
                {
                    b.HasOne("MediCore.API.Modules.Bed.Models.PatientAdmission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Doctor.Models.DoctorProfile", "FollowUpDoctor")
                        .WithMany()
                        .HasForeignKey("FollowUpWithDoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admission");

                    b.Navigation("FollowUpDoctor");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.PatientAdmission", b =>
                {
                    b.HasOne("MediCore.API.Modules.Doctor.Models.DoctorProfile", "AdmittingDoctor")
                        .WithMany()
                        .HasForeignKey("AdmittingDoctorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Bed.Models.BedAllocation", "Bed")
                        .WithMany("AllAdmissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediCore.API.Modules.Patient.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "DischargedByUser")
                        .WithMany()
                        .HasForeignKey("DischargedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "PatientUser")
                        .WithMany()
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Bed.Models.Room", "Room")
                        .WithMany("PatientAdmissions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Bed.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdmittingDoctor");

                    b.Navigation("Bed");

                    b.Navigation("Department");

                    b.Navigation("DischargedByUser");

                    b.Navigation("PatientUser");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.Room", b =>
                {
                    b.HasOne("MediCore.API.Modules.Bed.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("MediCore.API.Modules.Doctor.Models.DoctorLeave", b =>
                {
                    b.HasOne("MediCore.API.Modules.Doctor.Models.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");
                });

            modelBuilder.Entity("MediCore.API.Modules.Doctor.Models.DoctorProfile", b =>
                {
                    b.HasOne("MediCore.API.Modules.Patient.Models.Department", "Department")
                        .WithMany("DoctorProfiles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.API.Modules.Finance.Models.Bill", b =>
                {
                    b.HasOne("MediCore.API.Modules.OPD.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MediCore.API.Modules.Laboratory.Models.LabOrder", b =>
                {
                    b.HasOne("MediCore.API.Modules.OPD.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.Appointment", b =>
                {
                    b.HasOne("MediCore.API.Modules.Patient.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Doctor.Models.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "PatientUser")
                        .WithMany()
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("MediCore.API.Modules.OPD.Models.Prescription", b =>
                {
                    b.HasOne("MediCore.API.Modules.OPD.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.PatientFeedback", b =>
                {
                    b.HasOne("MediCore.API.Modules.OPD.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Doctor.Models.DoctorProfile", "DoctorProfile")
                        .WithMany()
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "PatientUser")
                        .WithMany()
                        .HasForeignKey("PatientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientUser");
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.PatientProfile", b =>
                {
                    b.HasOne("MediCore.API.Modules.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Auth.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.BedAllocation", b =>
                {
                    b.Navigation("AllAdmissions");
                });

            modelBuilder.Entity("MediCore.API.Modules.Bed.Models.Room", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("PatientAdmissions");
                });

            modelBuilder.Entity("MediCore.API.Modules.Patient.Models.Department", b =>
                {
                    b.Navigation("DoctorProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
